2022-08-15 00:16:41.143 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 00:16:41.143 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 01:00:38.712 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.712 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.754 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.754 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.796 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.796 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.827 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.827 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.861 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.861 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.891 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.891 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.914 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:00:38.914 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.378 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.378 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.432 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.432 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.500 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.500 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.564 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.564 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.627 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.627 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.763 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.763 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.828 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.828 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.856 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:01:37.856 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:02:55.654 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:02:55.654 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:02:55.691 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:02:55.691 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:02:55.711 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:02:55.711 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:02:55.720 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-2' (123145501421568):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165812736
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726268940>
           └ <peewee._atomic object at 0x7fd726268430>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726268940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726268940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:02:55.720 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-2' (123145501421568):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165812736
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726268940>
           └ <peewee._atomic object at 0x7fd726268430>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726268940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726268940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:05.854 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-7' (123145504104448):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165861632
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278b80>
           └ <peewee._atomic object at 0x7fd726278a00>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278b80>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278b80>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:05.854 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-7' (123145504104448):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165861632
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278b80>
           └ <peewee._atomic object at 0x7fd726278a00>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278b80>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278b80>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:20.556 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-6' (123145503567872):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165879552
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd7262781f0>
           └ <peewee._atomic object at 0x7fd726278ee0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd7262781f0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd7262781f0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:20.556 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-6' (123145503567872):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165879552
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd7262781f0>
           └ <peewee._atomic object at 0x7fd726278ee0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd7262781f0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd7262781f0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:25.603 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-8' (123145504641024):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165828864
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278af0>
           └ <peewee._atomic object at 0x7fd726278df0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:25.603 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-8' (123145504641024):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165828864
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278af0>
           └ <peewee._atomic object at 0x7fd726278df0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278af0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:30.627 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-9' (123145505177600):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165812224
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd7262783a0>
           └ <peewee._atomic object at 0x7fd726278ee0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd7262783a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd7262783a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:30.627 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-9' (123145505177600):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165812224
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd7262783a0>
           └ <peewee._atomic object at 0x7fd726278ee0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd7262783a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd7262783a0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:35.654 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-5' (123145503031296):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165913344
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278ca0>
           └ <peewee._atomic object at 0x7fd726278b20>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278ca0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278ca0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:35.654 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-5' (123145503031296):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165913344
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278ca0>
           └ <peewee._atomic object at 0x7fd726278b20>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278ca0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278ca0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:40.889 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-2' (123145501421568):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165894912
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd72624b640>
           └ <peewee._atomic object at 0x7fd72624ba00>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd72624b640>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd72624b640>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:40.889 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-2' (123145501421568):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165894912
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd72624b640>
           └ <peewee._atomic object at 0x7fd72624ba00>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd72624b640>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd72624b640>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:50.742 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-3' (123145501958144):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165929216
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd72624b640>
           └ <peewee._atomic object at 0x7fd72624b5e0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd72624b640>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd72624b640>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:50.742 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-3' (123145501958144):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165929216
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd72624b640>
           └ <peewee._atomic object at 0x7fd72624b5e0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd72624b640>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd72624b640>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:55.770 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-6' (123145503567872):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165828864
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726259d00>
           └ <peewee._atomic object at 0x7fd7262789d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726259d00>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726259d00>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:03:55.770 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-6' (123145503567872):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165828864
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726259d00>
           └ <peewee._atomic object at 0x7fd7262789d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726259d00>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726259d00>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:00.797 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-7' (123145504104448):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165895424
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278d90>
           └ <peewee._atomic object at 0x7fd726278130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278d90>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278d90>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:00.797 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-7' (123145504104448):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165895424
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278d90>
           └ <peewee._atomic object at 0x7fd726278130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278d90>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278d90>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:05.819 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-4' (123145502494720):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165880832
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278d30>
           └ <peewee._atomic object at 0x7fd7262781f0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278d30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278d30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:05.819 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-4' (123145502494720):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165880832
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278d30>
           └ <peewee._atomic object at 0x7fd7262781f0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278d30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278d30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:20.760 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-8' (123145504641024):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165928960
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278580>
           └ <peewee._atomic object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:20.760 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-8' (123145504641024):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165928960
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278580>
           └ <peewee._atomic object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278580>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:25.791 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-9' (123145505177600):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165880576
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278a30>
           └ <peewee._atomic object at 0x7fd7262783d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278a30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278a30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:25.791 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-9' (123145505177600):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165880576
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278a30>
           └ <peewee._atomic object at 0x7fd7262783d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278a30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278a30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:30.814 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-5' (123145503031296):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165880320
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278a30>
           └ <peewee._atomic object at 0x7fd7262785e0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278a30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278a30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:30.814 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-5' (123145503031296):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165880320
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278a30>
           └ <peewee._atomic object at 0x7fd7262785e0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278a30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278a30>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:35.840 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-2' (123145501421568):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165929728
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278be0>
           └ <peewee._atomic object at 0x7fd726278100>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:35.840 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-2' (123145501421568):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165929728
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278be0>
           └ <peewee._atomic object at 0x7fd726278100>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:40.912 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-3' (123145501958144):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165894400
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278be0>
           └ <peewee._atomic object at 0x7fd7262783d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:40.912 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60719), thread 'Dummy-3' (123145501958144):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553165894400
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function Reback at 0x7fd725ed9ee0>

  File "/Users/www/learn-note/gpmall/daoServer/inventory/handler/inventory.py", line 174, in Reback
    with DB.atomic() as txn:
         │  └ <function Database.atomic at 0x7fd7259ab0d0>
         └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4203, in __enter__
    return self._helper.__enter__()
           │    │       └ <function _transaction.__enter__ at 0x7fd7259b2280>
           │    └ <peewee._transaction object at 0x7fd726278be0>
           └ <peewee._atomic object at 0x7fd7262783d0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4230, in __enter__
    self._begin()
    │    └ <function _transaction._begin at 0x7fd7259b20d0>
    └ <peewee._transaction object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 4216, in _begin
    self.db.begin(*args, **kwargs)
    │    │  │      │       └ {}
    │    │  │      └ ()
    │    │  └ <function Database.begin at 0x7fd7259ab310>
    │    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    └ <peewee._transaction object at 0x7fd726278be0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3309, in begin
    self.connect()
    │    └ <function PooledDatabase.connect at 0x7fd7259de670>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 109, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
                 │               │             └ False
                 │               └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
                 └ <class 'playhouse.pool.PooledDatabase'>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3096, in connect
    self._state.set_connection(self._connect())
    │    │      │              │    └ <function PooledDatabase._connect at 0x7fd7259de700>
    │    │      │              └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
    │    │      └ <function _ConnectionState.set_connection at 0x7fd7259a3a60>
    │    └ <peewee._ConnectionLocal object at 0x7fd725b755e0>
    └ <config.config.ReconnectMysqlDatabase object at 0x7fd72589d880>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playhouse/pool.py", line 155, in _connect
    raise MaxConnectionsExceeded('Exceeded maximum connections.')
          └ <class 'playhouse.pool.MaxConnectionsExceeded'>

playhouse.pool.MaxConnectionsExceeded: Exceeded maximum connections.
2022-08-15 01:04:53.816 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 01:04:53.816 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 01:05:20.798 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:05:20.798 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:05:25.829 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:05:25.829 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:05:30.854 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:05:30.854 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:05:35.874 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:05:35.874 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:05:49.861 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 01:05:49.861 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 01:06:40.949 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:06:40.949 | INFO     | handler.inventory:Reback:193 - 库存记录不存在: ("<Model: inventory_history> instance matching query does not exist:\nSQL: SELECT `t1`.`id`, `t1`.`add_time`, `t1`.`update_time`, `t1`.`is_deleted`, `t1`.`order_sn`, `t1`.`order_inv_detail`, `t1`.`status` FROM `inventory_history` AS `t1` WHERE (((`t1`.`is_deleted` = %s) AND (`t1`.`order_sn` = %s)) AND (`t1`.`status` = %s)) LIMIT %s OFFSET %s\nParams: [False, '202208150023391663', 1, 1, 0]",)
2022-08-15 01:58:00.947 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 01:58:00.947 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 02:13:43.106 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 02:13:43.106 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 02:36:38.522 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 02:36:38.522 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 02:36:52.258 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 02:36:52.258 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 04:58:58.614 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 04:58:58.614 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 05:09:08.441 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 05:09:08.441 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 18:03:01.990 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 18:03:01.990 | INFO     | __main__:main:41 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 18:36:49.765 | INFO     | __main__:main:52 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 18:36:49.765 | INFO     | __main__:main:52 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 18:39:29.067 | INFO     | __main__:main:52 - inventory-dao服务启动: 192.168.8.222:4346
2022-08-15 18:39:29.067 | INFO     | __main__:main:52 - inventory-dao服务启动: 192.168.8.222:4346
