2022-08-03 02:38:00.962 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:38:00.962 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:38:00.962 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:38:21.673 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:38:21.673 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:38:21.673 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:47:46.416 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:47:46.416 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:47:46.416 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:51:32.693 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:51:32.693 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:51:32.693 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:55:27.643 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:55:27.643 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:55:27.643 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:55:43.289 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:55:43.289 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:55:43.289 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:56:52.160 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:56:52.160 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:56:52.160 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 02:56:59.126 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:56:59.126 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 02:56:59.126 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 03:07:55.101 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 03:07:55.101 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 03:07:55.101 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 03:11:19.853 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 03:11:19.853 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 03:11:19.853 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 03:11:21.471 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 03:11:21.471 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 03:11:21.471 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 03:12:09.018 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 03:12:09.018 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 03:12:09.018 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:19:19.549 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:19:19.549 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:19:19.549 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:19:26.132 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:19:26.132 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:19:26.132 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:19:57.166 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:19:57.166 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:19:57.166 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:20:04.229 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:20:04.229 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:20:04.229 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:23:05.419 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:23:05.419 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:23:05.419 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:25:47.149 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:25:47.149 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:25:47.149 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:25:50.188 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:25:50.188 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:25:50.188 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:26:04.674 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:26:04.674 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:26:04.674 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:28:28.487 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:28:28.487 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:28:28.487 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:28:35.878 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:28:35.878 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:28:35.878 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:29:27.659 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:29:27.659 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:29:27.659 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:29:30.002 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67206), thread 'ThreadPoolExecutor-0_0' (123145425477632):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff0876e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff0876e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
    │    │        │    └ (<weakref at 0x7ff08afa42c0; to 'ThreadPoolExecutor' at 0x7ff08af3fb80>, <_queue.SimpleQueue object at 0x7ff08af41e00>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
    │    └ <function _worker at 0x7ff08af56940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff08af56a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff08af96b80>, <grpc._server._RPCState object at 0x7ff08afa2070>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
             │    └ <function _unary_response_in_pool at 0x7ff08af93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7ff08af727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7ff08afa2070>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff08af96b80>
                        └ <function _call_behavior at 0x7ff08af91c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff08afa25e0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7ff08af727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 95, in CreateOrder
    context.set_detail(local_order_dict[orderSn]["detail"])
    │                  │                └ '202208030429291491'
    │                  └ {'202208030429291491': {'code': <StatusCode.OK: (0, 'ok')>, 'detail': '订单创建成功', 'order': {'id': 37, 'order_sn': '202208030429...
    └ <grpc._server._Context object at 0x7ff08afa25e0>

AttributeError: '_Context' object has no attribute 'set_detail'
2022-08-03 04:29:30.002 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67206), thread 'ThreadPoolExecutor-0_0' (123145425477632):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff0876e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff0876e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
    │    │        │    └ (<weakref at 0x7ff08afa42c0; to 'ThreadPoolExecutor' at 0x7ff08af3fb80>, <_queue.SimpleQueue object at 0x7ff08af41e00>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
    │    └ <function _worker at 0x7ff08af56940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff08af56a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff08af96b80>, <grpc._server._RPCState object at 0x7ff08afa2070>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
             │    └ <function _unary_response_in_pool at 0x7ff08af93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7ff08af727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7ff08afa2070>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff08af96b80>
                        └ <function _call_behavior at 0x7ff08af91c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff08afa25e0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7ff08af727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 95, in CreateOrder
    context.set_detail(local_order_dict[orderSn]["detail"])
    │                  │                └ '202208030429291491'
    │                  └ {'202208030429291491': {'code': <StatusCode.OK: (0, 'ok')>, 'detail': '订单创建成功', 'order': {'id': 37, 'order_sn': '202208030429...
    └ <grpc._server._Context object at 0x7ff08afa25e0>

AttributeError: '_Context' object has no attribute 'set_detail'
2022-08-03 04:29:30.002 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67206), thread 'ThreadPoolExecutor-0_0' (123145425477632):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff0876e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff0876e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
    │    │        │    └ (<weakref at 0x7ff08afa42c0; to 'ThreadPoolExecutor' at 0x7ff08af3fb80>, <_queue.SimpleQueue object at 0x7ff08af41e00>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
    │    └ <function _worker at 0x7ff08af56940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425477632)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff08af56a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff08af96b80>, <grpc._server._RPCState object at 0x7ff08afa2070>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
             │    └ <function _unary_response_in_pool at 0x7ff08af93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff08afa2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7ff08af727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7ff08afa2070>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff08af96b80>
                        └ <function _call_behavior at 0x7ff08af91c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff08afa25e0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7ff08af727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 95, in CreateOrder
    context.set_detail(local_order_dict[orderSn]["detail"])
    │                  │                └ '202208030429291491'
    │                  └ {'202208030429291491': {'code': <StatusCode.OK: (0, 'ok')>, 'detail': '订单创建成功', 'order': {'id': 37, 'order_sn': '202208030429...
    └ <grpc._server._Context object at 0x7ff08afa25e0>

AttributeError: '_Context' object has no attribute 'set_detail'
2022-08-03 04:29:37.209 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:29:37.209 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:29:37.209 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:31:08.056 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:31:08.056 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:31:08.056 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:31:35.285 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67309), thread 'ThreadPoolExecutor-0_0' (123145439940608):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f8b3eeccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f8b3eecc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
    │    │        │    └ (<weakref at 0x7f8b4167f1d0; to 'ThreadPoolExecutor' at 0x7f8b415ffb80>, <_queue.SimpleQueue object at 0x7f8b41612d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
    │    └ <function _worker at 0x7f8b41627940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f8b41627a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f8b41671f40>, <grpc._server._RPCState object at 0x7f8b4167d280>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
             │    └ <function _unary_response_in_pool at 0x7f8b4166d040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f8b416437c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f8b4167d280>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f8b41671f40>
                        └ <function _call_behavior at 0x7f8b4166cc10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f8b4167d550>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f8b416437c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 74, in CreateOrder
    p.start()
    │ └ <function TransactionMQProducer.start at 0x7f8b412de280>
    └ <rocketmq.client.TransactionMQProducer object at 0x7f8b4167d730>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 309, in start
    ffi_check(dll.StartProducer(self._handle))
    │         │   │             │    └ 105553154153632
    │         │   │             └ <rocketmq.client.TransactionMQProducer object at 0x7f8b4167d730>
    │         │   └ <_FuncPtr object at 0x7f8b412cec40>
    │         └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 218248140 at 0x7f8b412c5d60>
    └ <function ffi_check at 0x7f8b412cd280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'The producer group[transProducerGroup] has been created before, specify another name please.,error:-1,in file rocketmq-clien...
          └ <class 'rocketmq.exceptions.ProducerStartFailed'>

rocketmq.exceptions.ProducerStartFailed: The producer group[transProducerGroup] has been created before, specify another name please.,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp line:79
2022-08-03 04:31:35.285 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67309), thread 'ThreadPoolExecutor-0_0' (123145439940608):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f8b3eeccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f8b3eecc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
    │    │        │    └ (<weakref at 0x7f8b4167f1d0; to 'ThreadPoolExecutor' at 0x7f8b415ffb80>, <_queue.SimpleQueue object at 0x7f8b41612d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
    │    └ <function _worker at 0x7f8b41627940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f8b41627a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f8b41671f40>, <grpc._server._RPCState object at 0x7f8b4167d280>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
             │    └ <function _unary_response_in_pool at 0x7f8b4166d040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f8b416437c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f8b4167d280>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f8b41671f40>
                        └ <function _call_behavior at 0x7f8b4166cc10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f8b4167d550>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f8b416437c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 74, in CreateOrder
    p.start()
    │ └ <function TransactionMQProducer.start at 0x7f8b412de280>
    └ <rocketmq.client.TransactionMQProducer object at 0x7f8b4167d730>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 309, in start
    ffi_check(dll.StartProducer(self._handle))
    │         │   │             │    └ 105553154153632
    │         │   │             └ <rocketmq.client.TransactionMQProducer object at 0x7f8b4167d730>
    │         │   └ <_FuncPtr object at 0x7f8b412cec40>
    │         └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 218248140 at 0x7f8b412c5d60>
    └ <function ffi_check at 0x7f8b412cd280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'The producer group[transProducerGroup] has been created before, specify another name please.,error:-1,in file rocketmq-clien...
          └ <class 'rocketmq.exceptions.ProducerStartFailed'>

rocketmq.exceptions.ProducerStartFailed: The producer group[transProducerGroup] has been created before, specify another name please.,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp line:79
2022-08-03 04:31:35.285 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67309), thread 'ThreadPoolExecutor-0_0' (123145439940608):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f8b3eeccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f8b3eecc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
    │    │        │    └ (<weakref at 0x7f8b4167f1d0; to 'ThreadPoolExecutor' at 0x7f8b415ffb80>, <_queue.SimpleQueue object at 0x7f8b41612d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
    │    └ <function _worker at 0x7f8b41627940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145439940608)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f8b41627a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f8b41671f40>, <grpc._server._RPCState object at 0x7f8b4167d280>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
             │    └ <function _unary_response_in_pool at 0x7f8b4166d040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f8b4167d130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f8b416437c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f8b4167d280>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f8b41671f40>
                        └ <function _call_behavior at 0x7f8b4166cc10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f8b4167d550>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f8b416437c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 74, in CreateOrder
    p.start()
    │ └ <function TransactionMQProducer.start at 0x7f8b412de280>
    └ <rocketmq.client.TransactionMQProducer object at 0x7f8b4167d730>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 309, in start
    ffi_check(dll.StartProducer(self._handle))
    │         │   │             │    └ 105553154153632
    │         │   │             └ <rocketmq.client.TransactionMQProducer object at 0x7f8b4167d730>
    │         │   └ <_FuncPtr object at 0x7f8b412cec40>
    │         └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 218248140 at 0x7f8b412c5d60>
    └ <function ffi_check at 0x7f8b412cd280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/exceptions.py", line 44, in ffi_check
    raise exc_cls(msg)
          │       └ 'The producer group[transProducerGroup] has been created before, specify another name please.,error:-1,in file rocketmq-clien...
          └ <class 'rocketmq.exceptions.ProducerStartFailed'>

rocketmq.exceptions.ProducerStartFailed: The producer group[transProducerGroup] has been created before, specify another name please.,error:-1,in file rocketmq-client-cpp/src/producer/DefaultMQProducerImpl.cpp line:79
2022-08-03 04:31:37.643 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:31:37.643 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:31:37.643 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:31:56.230 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:31:56.230 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:31:56.230 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:32:55.827 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67368), thread 'ThreadPoolExecutor-0_0' (123145401618432):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbabf7e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbabf7e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
    │    │        │    └ (<weakref at 0x7fbac38a41d0; to 'ThreadPoolExecutor' at 0x7fbac383fb80>, <_queue.SimpleQueue object at 0x7fbac3842d10>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
    │    └ <function _worker at 0x7fbac3854940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbac3854a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbac3897a90>, <grpc._server._RPCState object at 0x7fbac38a27f0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
             │    └ <function _unary_response_in_pool at 0x7fbac3893040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fbac38727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbac38a27f0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbac3897a90>
                        └ <function _call_behavior at 0x7fbac3892c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbac38a2160>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fbac38727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE07285252CEFB0B4697C60002', offset=601)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-03 04:32:55.827 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67368), thread 'ThreadPoolExecutor-0_0' (123145401618432):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbabf7e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbabf7e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
    │    │        │    └ (<weakref at 0x7fbac38a41d0; to 'ThreadPoolExecutor' at 0x7fbac383fb80>, <_queue.SimpleQueue object at 0x7fbac3842d10>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
    │    └ <function _worker at 0x7fbac3854940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbac3854a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbac3897a90>, <grpc._server._RPCState object at 0x7fbac38a27f0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
             │    └ <function _unary_response_in_pool at 0x7fbac3893040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fbac38727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbac38a27f0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbac3897a90>
                        └ <function _call_behavior at 0x7fbac3892c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbac38a2160>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fbac38727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE07285252CEFB0B4697C60002', offset=601)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-03 04:32:55.827 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67368), thread 'ThreadPoolExecutor-0_0' (123145401618432):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbabf7e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbabf7e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
    │    │        │    └ (<weakref at 0x7fbac38a41d0; to 'ThreadPoolExecutor' at 0x7fbac383fb80>, <_queue.SimpleQueue object at 0x7fbac3842d10>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
    │    └ <function _worker at 0x7fbac3854940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145401618432)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbac3854a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbac3897a90>, <grpc._server._RPCState object at 0x7fbac38a27f0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
             │    └ <function _unary_response_in_pool at 0x7fbac3893040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbac38a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fbac38727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbac38a27f0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbac3897a90>
                        └ <function _call_behavior at 0x7fbac3892c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbac38a2160>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fbac38727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE07285252CEFB0B4697C60002', offset=601)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-03 04:35:03.395 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:35:03.395 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:35:03.395 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:36:04.047 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:36:04.047 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:36:04.047 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-03 04:36:30.272 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67608), thread 'ThreadPoolExecutor-0_0' (123145600466944):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc8dc0e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fc8dc0e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
    │    │        │    └ (<weakref at 0x7fc8dd886220; to 'ThreadPoolExecutor' at 0x7fc8dd810b80>, <_queue.SimpleQueue object at 0x7fc8dd824d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
    │    └ <function _worker at 0x7fc8dd8369d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fc8dd836af0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fc8dd878ea0>, <grpc._server._RPCState object at 0x7fc8dd884160>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
             │    └ <function _unary_response_in_pool at 0x7fc8dd8740d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fc8dd8547c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fc8dd884160>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fc8dd878ea0>
                        └ <function _call_behavior at 0x7fc8dd873ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fc8dd884670>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fc8dd8547c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='7F000001081852980D1D0B49DD5C0000', offset=602)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-03 04:36:30.272 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67608), thread 'ThreadPoolExecutor-0_0' (123145600466944):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc8dc0e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fc8dc0e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
    │    │        │    └ (<weakref at 0x7fc8dd886220; to 'ThreadPoolExecutor' at 0x7fc8dd810b80>, <_queue.SimpleQueue object at 0x7fc8dd824d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
    │    └ <function _worker at 0x7fc8dd8369d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fc8dd836af0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fc8dd878ea0>, <grpc._server._RPCState object at 0x7fc8dd884160>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
             │    └ <function _unary_response_in_pool at 0x7fc8dd8740d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fc8dd8547c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fc8dd884160>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fc8dd878ea0>
                        └ <function _call_behavior at 0x7fc8dd873ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fc8dd884670>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fc8dd8547c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='7F000001081852980D1D0B49DD5C0000', offset=602)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-03 04:36:30.272 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (67608), thread 'ThreadPoolExecutor-0_0' (123145600466944):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc8dc0e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fc8dc0e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
    │    │        │    └ (<weakref at 0x7fc8dd886220; to 'ThreadPoolExecutor' at 0x7fc8dd810b80>, <_queue.SimpleQueue object at 0x7fc8dd824d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
    │    └ <function _worker at 0x7fc8dd8369d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145600466944)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fc8dd836af0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fc8dd878ea0>, <grpc._server._RPCState object at 0x7fc8dd884160>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
             │    └ <function _unary_response_in_pool at 0x7fc8dd8740d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fc8dd8841c0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fc8dd8547c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fc8dd884160>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fc8dd878ea0>
                        └ <function _call_behavior at 0x7fc8dd873ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fc8dd884670>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fc8dd8547c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='7F000001081852980D1D0B49DD5C0000', offset=602)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-03 04:38:00.187 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:38:00.187 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-03 04:38:00.187 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
