2022-08-09 01:06:38.282 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:06:38.282 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:06:38.282 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:07:09.778 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (70847), thread 'ThreadPoolExecutor-0_0' (123145618558976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbba36cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbba36cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    │        │    └ (<weakref at 0x7fbba5f72a90; to 'ThreadPoolExecutor' at 0x7fbba5f14550>, <_queue.SimpleQueue object at 0x7fbba5f116d0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    └ <function _worker at 0x7fbba5f22af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbba5f22c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba5f729f0>, <grpc._server._RPCState object at 0x7fbba5f667c0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
             │    └ <function _unary_response_in_pool at 0x7fbba5f6e1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbba5f667c0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba5f729f0>
                        └ <function _call_behavior at 0x7fbba5f67dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbba5f7f1f0>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fbba5edd820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fbba5f49190>
    │      │   └ <peewee.FieldAccessor object at 0x7fbba5c1cb80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:07:09.778 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (70847), thread 'ThreadPoolExecutor-0_0' (123145618558976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbba36cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbba36cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    │        │    └ (<weakref at 0x7fbba5f72a90; to 'ThreadPoolExecutor' at 0x7fbba5f14550>, <_queue.SimpleQueue object at 0x7fbba5f116d0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    └ <function _worker at 0x7fbba5f22af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbba5f22c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba5f729f0>, <grpc._server._RPCState object at 0x7fbba5f667c0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
             │    └ <function _unary_response_in_pool at 0x7fbba5f6e1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbba5f667c0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba5f729f0>
                        └ <function _call_behavior at 0x7fbba5f67dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbba5f7f1f0>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fbba5edd820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fbba5f49190>
    │      │   └ <peewee.FieldAccessor object at 0x7fbba5c1cb80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:07:09.778 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (70847), thread 'ThreadPoolExecutor-0_0' (123145618558976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbba36cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbba36cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    │        │    └ (<weakref at 0x7fbba5f72a90; to 'ThreadPoolExecutor' at 0x7fbba5f14550>, <_queue.SimpleQueue object at 0x7fbba5f116d0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    └ <function _worker at 0x7fbba5f22af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbba5f22c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba5f729f0>, <grpc._server._RPCState object at 0x7fbba5f667c0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
             │    └ <function _unary_response_in_pool at 0x7fbba5f6e1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbba5f66940>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbba5f667c0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba5f729f0>
                        └ <function _call_behavior at 0x7fbba5f67dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbba5f7f1f0>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fbba5edd820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fbba5f49190>
    │      │   └ <peewee.FieldAccessor object at 0x7fbba5c1cb80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:07:55.766 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (70847), thread 'ThreadPoolExecutor-0_0' (123145618558976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbba36cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbba36cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    │        │    └ (<weakref at 0x7fbba5f72a90; to 'ThreadPoolExecutor' at 0x7fbba5f14550>, <_queue.SimpleQueue object at 0x7fbba5f116d0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    └ <function _worker at 0x7fbba5f22af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbba5f22c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba7910860>, <grpc._server._RPCState object at 0x7fbba5fa4c70>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
             │    └ <function _unary_response_in_pool at 0x7fbba5f6e1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbba5fa4c70>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba7910860>
                        └ <function _call_behavior at 0x7fbba5f67dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbba5fa4790>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fbba5edd820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fbba5f49190>
    │      │   └ <peewee.FieldAccessor object at 0x7fbba5c1cb80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:07:55.766 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (70847), thread 'ThreadPoolExecutor-0_0' (123145618558976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbba36cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbba36cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    │        │    └ (<weakref at 0x7fbba5f72a90; to 'ThreadPoolExecutor' at 0x7fbba5f14550>, <_queue.SimpleQueue object at 0x7fbba5f116d0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    └ <function _worker at 0x7fbba5f22af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbba5f22c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba7910860>, <grpc._server._RPCState object at 0x7fbba5fa4c70>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
             │    └ <function _unary_response_in_pool at 0x7fbba5f6e1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbba5fa4c70>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba7910860>
                        └ <function _call_behavior at 0x7fbba5f67dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbba5fa4790>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fbba5edd820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fbba5f49190>
    │      │   └ <peewee.FieldAccessor object at 0x7fbba5c1cb80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:07:55.766 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (70847), thread 'ThreadPoolExecutor-0_0' (123145618558976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fbba36cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fbba36cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    │        │    └ (<weakref at 0x7fbba5f72a90; to 'ThreadPoolExecutor' at 0x7fbba5f14550>, <_queue.SimpleQueue object at 0x7fbba5f116d0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
    │    └ <function _worker at 0x7fbba5f22af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145618558976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fbba5f22c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba7910860>, <grpc._server._RPCState object at 0x7fbba5fa4c70>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
             │    └ <function _unary_response_in_pool at 0x7fbba5f6e1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fbba5fa42b0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fbba5fa4c70>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fbba7910860>
                        └ <function _call_behavior at 0x7fbba5f67dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fbba5fa4790>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fbba5f49190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fbba5edd820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fbba5f49190>
    │      │   └ <peewee.FieldAccessor object at 0x7fbba5c1cb80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:11:31.124 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:11:31.124 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:11:31.124 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:11:32.784 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:11:32.784 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:11:32.784 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:11:35.943 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71164), thread 'ThreadPoolExecutor-0_0' (123145602347008):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd4496cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd4496cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
    │    │        │    └ (<weakref at 0x7fd44ce77bd0; to 'ThreadPoolExecutor' at 0x7fd44ce25550>, <_queue.SimpleQueue object at 0x7fd44ce22770>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
    │    └ <function _worker at 0x7fd44ce33af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fd44ce33c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fd44ce774f0>, <grpc._server._RPCState object at 0x7fd44ce6e940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
             │    └ <function _unary_response_in_pool at 0x7fd44ce741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fd44ce59190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fd44ce6e940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fd44ce774f0>
                        └ <function _call_behavior at 0x7fd44ce73dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fd44ce86160>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fd44ce59190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fd44cdee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fd44ce59190>
    │      │   └ <peewee.FieldAccessor object at 0x7fd44cc2db80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 71, in _transformToProto
    rsp.goods_id  = item.goods_id
    │   │           │    └ None
    │   │           └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.goods_id'>
    └ order_id: 26

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:11:35.943 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71164), thread 'ThreadPoolExecutor-0_0' (123145602347008):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd4496cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd4496cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
    │    │        │    └ (<weakref at 0x7fd44ce77bd0; to 'ThreadPoolExecutor' at 0x7fd44ce25550>, <_queue.SimpleQueue object at 0x7fd44ce22770>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
    │    └ <function _worker at 0x7fd44ce33af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fd44ce33c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fd44ce774f0>, <grpc._server._RPCState object at 0x7fd44ce6e940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
             │    └ <function _unary_response_in_pool at 0x7fd44ce741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fd44ce59190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fd44ce6e940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fd44ce774f0>
                        └ <function _call_behavior at 0x7fd44ce73dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fd44ce86160>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fd44ce59190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fd44cdee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fd44ce59190>
    │      │   └ <peewee.FieldAccessor object at 0x7fd44cc2db80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 71, in _transformToProto
    rsp.goods_id  = item.goods_id
    │   │           │    └ None
    │   │           └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.goods_id'>
    └ order_id: 26

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:11:35.943 | ERROR    | handler.order:QueryOrderList:343 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71164), thread 'ThreadPoolExecutor-0_0' (123145602347008):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd4496cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fd4496cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
    │    │        │    └ (<weakref at 0x7fd44ce77bd0; to 'ThreadPoolExecutor' at 0x7fd44ce25550>, <_queue.SimpleQueue object at 0x7fd44ce22770>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
    │    └ <function _worker at 0x7fd44ce33af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145602347008)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fd44ce33c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fd44ce774f0>, <grpc._server._RPCState object at 0x7fd44ce6e940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
             │    └ <function _unary_response_in_pool at 0x7fd44ce741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fd44ce6e700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fd44ce59190>>
                        │              │          └ <grpc._server._RPCState object at 0x7fd44ce6e940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fd44ce774f0>
                        └ <function _call_behavior at 0x7fd44ce73dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fd44ce86160>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fd44ce59190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 343, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fd44cdee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fd44ce59190>
    │      │   └ <peewee.FieldAccessor object at 0x7fd44cc2db80>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 71, in _transformToProto
    rsp.goods_id  = item.goods_id
    │   │           │    └ None
    │   │           └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.goods_id'>
    └ order_id: 26

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:13:04.129 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:13:04.129 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:13:04.129 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:13:08.731 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:13:08.731 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:13:08.731 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:13:11.248 | ERROR    | handler.order:QueryOrderList:344 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71258), thread 'ThreadPoolExecutor-0_0' (123145552097280):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9ac67e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9ac67e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
    │    │        │    └ (<weakref at 0x7f9aca795b30; to 'ThreadPoolExecutor' at 0x7f9aca743550>, <_queue.SimpleQueue object at 0x7f9aca740720>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
    │    └ <function _worker at 0x7f9aca752af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9aca752c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9aca795450>, <grpc._server._RPCState object at 0x7f9aca794940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
             │    └ <function _unary_response_in_pool at 0x7f9aca7921f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f9aca777190>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9aca794940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9aca795450>
                        └ <function _call_behavior at 0x7f9aca78bdc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9aca7a4160>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f9aca777190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 344, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7f9aca71d820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7f9aca777190>
    │      │   └ <peewee.FieldAccessor object at 0x7f9aca45abe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 71, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:13:11.248 | ERROR    | handler.order:QueryOrderList:344 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71258), thread 'ThreadPoolExecutor-0_0' (123145552097280):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9ac67e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9ac67e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
    │    │        │    └ (<weakref at 0x7f9aca795b30; to 'ThreadPoolExecutor' at 0x7f9aca743550>, <_queue.SimpleQueue object at 0x7f9aca740720>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
    │    └ <function _worker at 0x7f9aca752af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9aca752c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9aca795450>, <grpc._server._RPCState object at 0x7f9aca794940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
             │    └ <function _unary_response_in_pool at 0x7f9aca7921f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f9aca777190>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9aca794940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9aca795450>
                        └ <function _call_behavior at 0x7f9aca78bdc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9aca7a4160>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f9aca777190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 344, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7f9aca71d820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7f9aca777190>
    │      │   └ <peewee.FieldAccessor object at 0x7f9aca45abe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 71, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:13:11.248 | ERROR    | handler.order:QueryOrderList:344 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71258), thread 'ThreadPoolExecutor-0_0' (123145552097280):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9ac67e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9ac67e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
    │    │        │    └ (<weakref at 0x7f9aca795b30; to 'ThreadPoolExecutor' at 0x7f9aca743550>, <_queue.SimpleQueue object at 0x7f9aca740720>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
    │    └ <function _worker at 0x7f9aca752af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145552097280)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9aca752c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9aca795450>, <grpc._server._RPCState object at 0x7f9aca794940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
             │    └ <function _unary_response_in_pool at 0x7f9aca7921f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9aca794700>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f9aca777190>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9aca794940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9aca795450>
                        └ <function _call_behavior at 0x7f9aca78bdc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9aca7a4160>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f9aca777190>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 344, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7f9aca71d820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7f9aca777190>
    │      │   └ <peewee.FieldAccessor object at 0x7f9aca45abe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 71, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:14:15.661 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:14:15.661 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:14:15.661 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:14:17.618 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:14:17.618 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:14:17.618 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:14:19.346 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71328), thread 'ThreadPoolExecutor-0_0' (123145608564736):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff39b8e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff39b8e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
    │    │        │    └ (<weakref at 0x7ff39c777a90; to 'ThreadPoolExecutor' at 0x7ff39c725520>, <_queue.SimpleQueue object at 0x7ff39c722680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
    │    └ <function _worker at 0x7ff39c734af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff39c734c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff39c7773b0>, <grpc._server._RPCState object at 0x7ff39c76c940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
             │    └ <function _unary_response_in_pool at 0x7ff39c7741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7ff39c759160>>
                        │              │          └ <grpc._server._RPCState object at 0x7ff39c76c940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff39c7773b0>
                        └ <function _call_behavior at 0x7ff39c76ddc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff39c787100>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7ff39c759160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7ff39c6ee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7ff39c759160>
    │      │   └ <peewee.FieldAccessor object at 0x7ff39c52dbe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:14:19.346 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71328), thread 'ThreadPoolExecutor-0_0' (123145608564736):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff39b8e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff39b8e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
    │    │        │    └ (<weakref at 0x7ff39c777a90; to 'ThreadPoolExecutor' at 0x7ff39c725520>, <_queue.SimpleQueue object at 0x7ff39c722680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
    │    └ <function _worker at 0x7ff39c734af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff39c734c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff39c7773b0>, <grpc._server._RPCState object at 0x7ff39c76c940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
             │    └ <function _unary_response_in_pool at 0x7ff39c7741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7ff39c759160>>
                        │              │          └ <grpc._server._RPCState object at 0x7ff39c76c940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff39c7773b0>
                        └ <function _call_behavior at 0x7ff39c76ddc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff39c787100>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7ff39c759160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7ff39c6ee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7ff39c759160>
    │      │   └ <peewee.FieldAccessor object at 0x7ff39c52dbe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:14:19.346 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71328), thread 'ThreadPoolExecutor-0_0' (123145608564736):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ff39b8e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ff39b8e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
    │    │        │    └ (<weakref at 0x7ff39c777a90; to 'ThreadPoolExecutor' at 0x7ff39c725520>, <_queue.SimpleQueue object at 0x7ff39c722680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
    │    └ <function _worker at 0x7ff39c734af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145608564736)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7ff39c734c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7ff39c7773b0>, <grpc._server._RPCState object at 0x7ff39c76c940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
             │    └ <function _unary_response_in_pool at 0x7ff39c7741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7ff39c76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7ff39c759160>>
                        │              │          └ <grpc._server._RPCState object at 0x7ff39c76c940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7ff39c7773b0>
                        └ <function _call_behavior at 0x7ff39c76ddc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7ff39c787100>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7ff39c759160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7ff39c6ee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7ff39c759160>
    │      │   └ <peewee.FieldAccessor object at 0x7ff39c52dbe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:15:44.024 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:15:44.024 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:15:44.024 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:15:46.055 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:15:46.055 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:15:46.055 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:15:48.113 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71414), thread 'ThreadPoolExecutor-0_0' (123145481555968):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9109fcbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9109fcb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
    │    │        │    └ (<weakref at 0x7f910d777ae0; to 'ThreadPoolExecutor' at 0x7f910d725520>, <_queue.SimpleQueue object at 0x7f910d722680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
    │    └ <function _worker at 0x7f910d734af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f910d734c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f910d777400>, <grpc._server._RPCState object at 0x7f910d76c940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
             │    └ <function _unary_response_in_pool at 0x7f910d7741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f910d759160>>
                        │              │          └ <grpc._server._RPCState object at 0x7f910d76c940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f910d777400>
                        └ <function _call_behavior at 0x7f910d76ddc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f910d787130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f910d759160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 1>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7f910d6ee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7f910d759160>
    │      │   └ <peewee.FieldAccessor object at 0x7f910d52db80>
    │      └ <order_info: 1>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    print("--------|| --------", item["order_id"])
                                 └ <order_info: 1>

TypeError: 'order_info' object is not subscriptable
2022-08-09 01:15:48.113 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71414), thread 'ThreadPoolExecutor-0_0' (123145481555968):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9109fcbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9109fcb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
    │    │        │    └ (<weakref at 0x7f910d777ae0; to 'ThreadPoolExecutor' at 0x7f910d725520>, <_queue.SimpleQueue object at 0x7f910d722680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
    │    └ <function _worker at 0x7f910d734af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f910d734c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f910d777400>, <grpc._server._RPCState object at 0x7f910d76c940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
             │    └ <function _unary_response_in_pool at 0x7f910d7741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f910d759160>>
                        │              │          └ <grpc._server._RPCState object at 0x7f910d76c940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f910d777400>
                        └ <function _call_behavior at 0x7f910d76ddc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f910d787130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f910d759160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 1>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7f910d6ee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7f910d759160>
    │      │   └ <peewee.FieldAccessor object at 0x7f910d52db80>
    │      └ <order_info: 1>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    print("--------|| --------", item["order_id"])
                                 └ <order_info: 1>

TypeError: 'order_info' object is not subscriptable
2022-08-09 01:15:48.113 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71414), thread 'ThreadPoolExecutor-0_0' (123145481555968):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9109fcbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9109fcb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
    │    │        │    └ (<weakref at 0x7f910d777ae0; to 'ThreadPoolExecutor' at 0x7f910d725520>, <_queue.SimpleQueue object at 0x7f910d722680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
    │    └ <function _worker at 0x7f910d734af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145481555968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f910d734c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f910d777400>, <grpc._server._RPCState object at 0x7f910d76c940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
             │    └ <function _unary_response_in_pool at 0x7f910d7741f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7f910d76c790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f910d759160>>
                        │              │          └ <grpc._server._RPCState object at 0x7f910d76c940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f910d777400>
                        └ <function _call_behavior at 0x7f910d76ddc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f910d787130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7f910d759160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 1>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7f910d6ee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7f910d759160>
    │      │   └ <peewee.FieldAccessor object at 0x7f910d52db80>
    │      └ <order_info: 1>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 70, in _transformToProto
    print("--------|| --------", item["order_id"])
                                 └ <order_info: 1>

TypeError: 'order_info' object is not subscriptable
2022-08-09 01:16:52.223 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:16:52.223 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:16:52.223 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:16:55.952 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:16:55.952 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:16:55.952 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:16:58.356 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71489), thread 'ThreadPoolExecutor-0_0' (123145553915904):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe1456e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe1456e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
    │    │        │    └ (<weakref at 0x7fe149697b30; to 'ThreadPoolExecutor' at 0x7fe149643520>, <_queue.SimpleQueue object at 0x7fe149640720>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
    │    └ <function _worker at 0x7fe149652af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe149652c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe1496974a0>, <grpc._server._RPCState object at 0x7fe14968b940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
             │    └ <function _unary_response_in_pool at 0x7fe1496921f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fe149678160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe14968b940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe1496974a0>
                        └ <function _call_behavior at 0x7fe149691dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe1496a5130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fe149678160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fe14961d820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fe149678160>
    │      │   └ <peewee.FieldAccessor object at 0x7fe14945cbb0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:16:58.356 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71489), thread 'ThreadPoolExecutor-0_0' (123145553915904):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe1456e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe1456e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
    │    │        │    └ (<weakref at 0x7fe149697b30; to 'ThreadPoolExecutor' at 0x7fe149643520>, <_queue.SimpleQueue object at 0x7fe149640720>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
    │    └ <function _worker at 0x7fe149652af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe149652c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe1496974a0>, <grpc._server._RPCState object at 0x7fe14968b940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
             │    └ <function _unary_response_in_pool at 0x7fe1496921f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fe149678160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe14968b940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe1496974a0>
                        └ <function _call_behavior at 0x7fe149691dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe1496a5130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fe149678160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fe14961d820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fe149678160>
    │      │   └ <peewee.FieldAccessor object at 0x7fe14945cbb0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:16:58.356 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71489), thread 'ThreadPoolExecutor-0_0' (123145553915904):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe1456e6c10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe1456e6940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
    │    │        │    └ (<weakref at 0x7fe149697b30; to 'ThreadPoolExecutor' at 0x7fe149643520>, <_queue.SimpleQueue object at 0x7fe149640720>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
    │    └ <function _worker at 0x7fe149652af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145553915904)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe149652c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe1496974a0>, <grpc._server._RPCState object at 0x7fe14968b940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
             │    └ <function _unary_response_in_pool at 0x7fe1496921f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe14968b790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fe149678160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe14968b940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe1496974a0>
                        └ <function _call_behavior at 0x7fe149691dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe1496a5130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fe149678160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fe14961d820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fe149678160>
    │      │   └ <peewee.FieldAccessor object at 0x7fe14945cbb0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:18:20.111 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:18:20.111 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:18:20.111 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:18:23.924 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:18:23.924 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:18:23.924 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:18:26.026 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71574), thread 'ThreadPoolExecutor-0_0' (123145373171712):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc2a0ecbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fc2a0ecb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
    │    │        │    └ (<weakref at 0x7fc2a5077b30; to 'ThreadPoolExecutor' at 0x7fc2a5025520>, <_queue.SimpleQueue object at 0x7fc2a5022770>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
    │    └ <function _worker at 0x7fc2a5034af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fc2a5034c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fc2a5077450>, <grpc._server._RPCState object at 0x7fc2a506e940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
             │    └ <function _unary_response_in_pool at 0x7fc2a50751f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fc2a505a160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fc2a506e940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fc2a5077450>
                        └ <function _call_behavior at 0x7fc2a5073dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fc2a5087130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fc2a505a160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fc2a4fee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fc2a505a160>
    │      │   └ <peewee.FieldAccessor object at 0x7fc2a4e2dbe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:18:26.026 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71574), thread 'ThreadPoolExecutor-0_0' (123145373171712):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc2a0ecbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fc2a0ecb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
    │    │        │    └ (<weakref at 0x7fc2a5077b30; to 'ThreadPoolExecutor' at 0x7fc2a5025520>, <_queue.SimpleQueue object at 0x7fc2a5022770>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
    │    └ <function _worker at 0x7fc2a5034af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fc2a5034c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fc2a5077450>, <grpc._server._RPCState object at 0x7fc2a506e940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
             │    └ <function _unary_response_in_pool at 0x7fc2a50751f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fc2a505a160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fc2a506e940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fc2a5077450>
                        └ <function _call_behavior at 0x7fc2a5073dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fc2a5087130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fc2a505a160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fc2a4fee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fc2a505a160>
    │      │   └ <peewee.FieldAccessor object at 0x7fc2a4e2dbe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:18:26.026 | ERROR    | handler.order:QueryOrderList:345 - An error has been caught in function 'QueryOrderList', process 'MainProcess' (71574), thread 'ThreadPoolExecutor-0_0' (123145373171712):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc2a0ecbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fc2a0ecb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
    │    │        │    └ (<weakref at 0x7fc2a5077b30; to 'ThreadPoolExecutor' at 0x7fc2a5025520>, <_queue.SimpleQueue object at 0x7fc2a5022770>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
    │    └ <function _worker at 0x7fc2a5034af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145373171712)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fc2a5034c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fc2a5077450>, <grpc._server._RPCState object at 0x7fc2a506e940>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
             │    └ <function _unary_response_in_pool at 0x7fc2a50751f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fc2a506e790>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fc2a505a160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fc2a506e940>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fc2a5077450>
                        └ <function _call_behavior at 0x7fc2a5073dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fc2a5087130>
                           │        └ user_id: 1
                           │          
                           └ <bound method OrderServicer.QueryOrderList of <handler.order.OrderServicer object at 0x7fc2a505a160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 345, in QueryOrderList
    exists[row.id].goods.append(self._transformToProto(row))
    │      │   │                │    │                 └ <order_info: 26>
    │      │   │                │    └ <function OrderServicer._transformToProto at 0x7fc2a4fee820>
    │      │   │                └ <handler.order.OrderServicer object at 0x7fc2a505a160>
    │      │   └ <peewee.FieldAccessor object at 0x7fc2a4e2dbe0>
    │      └ <order_info: 26>
    └ {1: id: 1
      order_sn: "202204151702181163"
      user_id: 1
      signer_mobile: "17887287878"
      amount: 20.0
      pay_amount: 20.0
      status: "0"
      pa...

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 72, in _transformToProto
    rsp.order_id = item.order_id
    │   │          │    └ None
    │   │          └ <order_info: 26>
    │   └ <field property 'OrderGoodsDetailResponse.order_id'>
    └

TypeError: None has type NoneType, but expected one of: int, long
2022-08-09 01:23:49.790 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:23:49.790 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:23:49.790 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:23:52.556 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:23:52.556 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:23:52.556 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:24:20.749 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:24:20.749 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:24:20.749 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:24:21.886 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:24:21.886 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:24:21.886 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:30:27.969 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:30:27.969 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:30:27.969 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:30:29.288 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:30:29.288 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:30:29.288 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 01:39:35.002 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:39:35.002 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 01:39:35.002 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 03:05:12.498 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 03:05:12.498 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 03:05:12.498 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 03:09:13.135 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 03:09:13.135 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 03:09:13.135 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-09 03:09:14.281 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 03:09:14.281 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 03:09:14.281 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-09 14:12:18.874 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
