2022-08-04 00:03:12.120 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:03:12.120 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:03:12.120 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:04:26.448 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (17392), thread 'ThreadPoolExecutor-0_0' (123145566834688):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb23daccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb23dacc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
    │    │        │    └ (<weakref at 0x7fb23e778130; to 'ThreadPoolExecutor' at 0x7fb23e6f9a90>, <_queue.SimpleQueue object at 0x7fb239ae6270>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
    │    └ <function _worker at 0x7fb23e71e9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb23e71eaf0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb23e76ce00>, <grpc._server._RPCState object at 0x7fb23e777850>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
             │    └ <function _unary_response_in_pool at 0x7fb23e7680d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fb23e73d730>>
                        │              │          └ <grpc._server._RPCState object at 0x7fb23e777850>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb23e76ce00>
                        └ <function _call_behavior at 0x7fb23e766ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb23e777070>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fb23e73d730>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE43F018B967180F7723560003', offset=606)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:04:26.448 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (17392), thread 'ThreadPoolExecutor-0_0' (123145566834688):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb23daccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb23dacc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
    │    │        │    └ (<weakref at 0x7fb23e778130; to 'ThreadPoolExecutor' at 0x7fb23e6f9a90>, <_queue.SimpleQueue object at 0x7fb239ae6270>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
    │    └ <function _worker at 0x7fb23e71e9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb23e71eaf0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb23e76ce00>, <grpc._server._RPCState object at 0x7fb23e777850>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
             │    └ <function _unary_response_in_pool at 0x7fb23e7680d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fb23e73d730>>
                        │              │          └ <grpc._server._RPCState object at 0x7fb23e777850>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb23e76ce00>
                        └ <function _call_behavior at 0x7fb23e766ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb23e777070>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fb23e73d730>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE43F018B967180F7723560003', offset=606)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:04:26.448 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (17392), thread 'ThreadPoolExecutor-0_0' (123145566834688):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb23daccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb23dacc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
    │    │        │    └ (<weakref at 0x7fb23e778130; to 'ThreadPoolExecutor' at 0x7fb23e6f9a90>, <_queue.SimpleQueue object at 0x7fb239ae6270>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
    │    └ <function _worker at 0x7fb23e71e9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145566834688)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fb23e71eaf0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fb23e76ce00>, <grpc._server._RPCState object at 0x7fb23e777850>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
             │    └ <function _unary_response_in_pool at 0x7fb23e7680d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fb23e777760>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fb23e73d730>>
                        │              │          └ <grpc._server._RPCState object at 0x7fb23e777850>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fb23e76ce00>
                        └ <function _call_behavior at 0x7fb23e766ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fb23e777070>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fb23e73d730>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE43F018B967180F7723560003', offset=606)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:05:13.667 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:05:13.667 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:05:13.667 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:28:36.187 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:28:36.187 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:28:36.187 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:28:59.556 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (19117), thread 'ThreadPoolExecutor-0_0' (123145557741568):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe7486e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe7486e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
    │    │        │    └ (<weakref at 0x7fe74bd851d0; to 'ThreadPoolExecutor' at 0x7fe74bd10a90>, <_queue.SimpleQueue object at 0x7fe74bd24db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
    │    └ <function _worker at 0x7fe74bd369d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe74bd36af0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe74bd79ea0>, <grpc._server._RPCState object at 0x7fe74bd84040>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
             │    └ <function _unary_response_in_pool at 0x7fe74bd750d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe74bd54730>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe74bd84040>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe74bd79ea0>
                        └ <function _call_behavior at 0x7fe74bd73ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe74bd841c0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe74bd54730>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE4AAD1A40C0920F8D9E000001', offset=608)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:28:59.556 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (19117), thread 'ThreadPoolExecutor-0_0' (123145557741568):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe7486e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe7486e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
    │    │        │    └ (<weakref at 0x7fe74bd851d0; to 'ThreadPoolExecutor' at 0x7fe74bd10a90>, <_queue.SimpleQueue object at 0x7fe74bd24db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
    │    └ <function _worker at 0x7fe74bd369d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe74bd36af0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe74bd79ea0>, <grpc._server._RPCState object at 0x7fe74bd84040>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
             │    └ <function _unary_response_in_pool at 0x7fe74bd750d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe74bd54730>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe74bd84040>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe74bd79ea0>
                        └ <function _call_behavior at 0x7fe74bd73ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe74bd841c0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe74bd54730>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE4AAD1A40C0920F8D9E000001', offset=608)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:28:59.556 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (19117), thread 'ThreadPoolExecutor-0_0' (123145557741568):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe7486e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe7486e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
    │    │        │    └ (<weakref at 0x7fe74bd851d0; to 'ThreadPoolExecutor' at 0x7fe74bd10a90>, <_queue.SimpleQueue object at 0x7fe74bd24db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
    │    └ <function _worker at 0x7fe74bd369d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145557741568)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe74bd36af0>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe74bd79ea0>, <grpc._server._RPCState object at 0x7fe74bd84040>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
             │    └ <function _unary_response_in_pool at 0x7fe74bd750d0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe74bd84130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe74bd54730>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe74bd84040>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe74bd79ea0>
                        └ <function _call_behavior at 0x7fe74bd73ca0>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe74bd841c0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe74bd54730>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 97, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE4AAD1A40C0920F8D9E000001', offset=608)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:31:22.681 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:31:22.681 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:31:22.681 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:33:19.201 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:33:19.201 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:33:19.201 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:33:49.564 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:33:49.564 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:33:49.564 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:33:51.740 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:33:51.740 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:33:51.740 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:35:29.872 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:35:29.872 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:35:29.872 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:35:31.381 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:35:31.381 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:35:31.381 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:36:48.539 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:36:48.539 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:36:48.539 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:36:50.869 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:36:50.869 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:36:50.869 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 00:37:11.156 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (19689), thread 'ThreadPoolExecutor-0_0' (123145544101888):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9b57dc2ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9b57dc29d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
    │    │        │    └ (<weakref at 0x7f9b5ada4270; to 'ThreadPoolExecutor' at 0x7f9b5ad3fb80>, <_queue.SimpleQueue object at 0x7f9b5ad41db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
    │    └ <function _worker at 0x7f9b5ad56940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9b5ad56a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9b5ad96b30>, <grpc._server._RPCState object at 0x7f9b5ada2220>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
             │    └ <function _unary_response_in_pool at 0x7f9b5ad93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9b5ad727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9b5ada2220>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9b5ad96b30>
                        └ <function _call_behavior at 0x7f9b5ad91c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9b5ada2130>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9b5ad727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 98, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE4CE91AC307F60F951EAB0000', offset=612)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:37:11.156 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (19689), thread 'ThreadPoolExecutor-0_0' (123145544101888):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9b57dc2ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9b57dc29d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
    │    │        │    └ (<weakref at 0x7f9b5ada4270; to 'ThreadPoolExecutor' at 0x7f9b5ad3fb80>, <_queue.SimpleQueue object at 0x7f9b5ad41db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
    │    └ <function _worker at 0x7f9b5ad56940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9b5ad56a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9b5ad96b30>, <grpc._server._RPCState object at 0x7f9b5ada2220>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
             │    └ <function _unary_response_in_pool at 0x7f9b5ad93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9b5ad727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9b5ada2220>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9b5ad96b30>
                        └ <function _call_behavior at 0x7f9b5ad91c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9b5ada2130>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9b5ad727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 98, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE4CE91AC307F60F951EAB0000', offset=612)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:37:11.156 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (19689), thread 'ThreadPoolExecutor-0_0' (123145544101888):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9b57dc2ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9b57dc29d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
    │    │        │    └ (<weakref at 0x7f9b5ada4270; to 'ThreadPoolExecutor' at 0x7f9b5ad3fb80>, <_queue.SimpleQueue object at 0x7f9b5ad41db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
    │    └ <function _worker at 0x7f9b5ad56940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544101888)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9b5ad56a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9b5ad96b30>, <grpc._server._RPCState object at 0x7f9b5ada2220>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
             │    └ <function _unary_response_in_pool at 0x7f9b5ad93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9b5ada2280>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9b5ad727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9b5ada2220>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9b5ad96b30>
                        └ <function _call_behavior at 0x7f9b5ad91c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9b5ada2130>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9b5ad727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 98, in CreateOrder
    id=res.order_id,
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE4CE91AC307F60F951EAB0000', offset=612)

AttributeError: 'SendResult' object has no attribute 'order_id'
2022-08-04 00:42:29.155 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:42:29.155 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 00:42:29.155 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 01:09:23.792 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 01:09:23.792 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 01:09:23.792 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 01:09:57.106 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 01:09:57.106 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 01:09:57.106 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 01:30:58.187 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 01:30:58.187 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 01:30:58.187 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 01:31:35.544 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 01:31:35.544 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 01:31:35.544 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:13:31.414 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:13:31.414 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:13:31.414 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:16:56.704 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (26328), thread 'ThreadPoolExecutor-0_0' (123145340030976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7fad6e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f7fad6e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
    │    │        │    └ (<weakref at 0x7f7fb18a41d0; to 'ThreadPoolExecutor' at 0x7f7fb183fb80>, <_queue.SimpleQueue object at 0x7f7fb1842d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
    │    └ <function _worker at 0x7f7fb1856940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f7fb1856a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f7fb1897f40>, <grpc._server._RPCState object at 0x7f7fb18a2880>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
             │    └ <function _unary_response_in_pool at 0x7f7fb1893040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f7fb18727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f7fb18a2880>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f7fb1897f40>
                        └ <function _call_behavior at 0x7f7fb1891c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f7fb18a20d0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f7fb18727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 99, in CreateOrder
    id = local_order_dict[orderSn]["order_id"].id,
         │                └ '202208040316561824'
         └ {'202208040313381453': {'code': <StatusCode.NOT_FOUND: (5, 'not found')>, 'detail': '没有选择购物车商品'}, '202208040316561824': {'cod...

KeyError: 'order_id'
2022-08-04 03:16:56.704 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (26328), thread 'ThreadPoolExecutor-0_0' (123145340030976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7fad6e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f7fad6e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
    │    │        │    └ (<weakref at 0x7f7fb18a41d0; to 'ThreadPoolExecutor' at 0x7f7fb183fb80>, <_queue.SimpleQueue object at 0x7f7fb1842d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
    │    └ <function _worker at 0x7f7fb1856940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f7fb1856a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f7fb1897f40>, <grpc._server._RPCState object at 0x7f7fb18a2880>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
             │    └ <function _unary_response_in_pool at 0x7f7fb1893040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f7fb18727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f7fb18a2880>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f7fb1897f40>
                        └ <function _call_behavior at 0x7f7fb1891c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f7fb18a20d0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f7fb18727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 99, in CreateOrder
    id = local_order_dict[orderSn]["order_id"].id,
         │                └ '202208040316561824'
         └ {'202208040313381453': {'code': <StatusCode.NOT_FOUND: (5, 'not found')>, 'detail': '没有选择购物车商品'}, '202208040316561824': {'cod...

KeyError: 'order_id'
2022-08-04 03:16:56.704 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (26328), thread 'ThreadPoolExecutor-0_0' (123145340030976):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7fad6e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f7fad6e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
    │    │        │    └ (<weakref at 0x7f7fb18a41d0; to 'ThreadPoolExecutor' at 0x7f7fb183fb80>, <_queue.SimpleQueue object at 0x7f7fb1842d60>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
    │    └ <function _worker at 0x7f7fb1856940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145340030976)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f7fb1856a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f7fb1897f40>, <grpc._server._RPCState object at 0x7f7fb18a2880>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
             │    └ <function _unary_response_in_pool at 0x7f7fb1893040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f7fb18a2250>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f7fb18727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f7fb18a2880>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f7fb1897f40>
                        └ <function _call_behavior at 0x7f7fb1891c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f7fb18a20d0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f7fb18727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 99, in CreateOrder
    id = local_order_dict[orderSn]["order_id"].id,
         │                └ '202208040316561824'
         └ {'202208040313381453': {'code': <StatusCode.NOT_FOUND: (5, 'not found')>, 'detail': '没有选择购物车商品'}, '202208040316561824': {'cod...

KeyError: 'order_id'
2022-08-04 03:37:07.777 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:37:07.777 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:37:07.777 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:37:09.235 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:37:09.235 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:37:09.235 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:37:33.002 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27727), thread 'ThreadPoolExecutor-0_0' (123145425432576):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe69fee7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe69fee79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
    │    │        │    └ (<weakref at 0x7fe6a1ea42c0; to 'ThreadPoolExecutor' at 0x7fe6a1e3fb80>, <_queue.SimpleQueue object at 0x7fe6a1e42e00>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
    │    └ <function _worker at 0x7fe6a1e55940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe6a1e55a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe6a1e96f40>, <grpc._server._RPCState object at 0x7fe6a1ea2190>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
             │    └ <function _unary_response_in_pool at 0x7fe6a1e93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe6a1e727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe6a1ea2190>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe6a1e96f40>
                        └ <function _call_behavior at 0x7fe6a1e92c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe6a1ea2100>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe6a1e727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 99, in CreateOrder
    id = local_order_dict[orderSn]["order"].id,
         │                └ '202208040337321236'
         └ {'202208040337151747': {'code': <StatusCode.NOT_FOUND: (5, 'not found')>, 'detail': '没有选择购物车商品'}, '202208040337321236': {'cod...

AttributeError: 'dict' object has no attribute 'id'
2022-08-04 03:37:33.002 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27727), thread 'ThreadPoolExecutor-0_0' (123145425432576):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe69fee7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe69fee79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
    │    │        │    └ (<weakref at 0x7fe6a1ea42c0; to 'ThreadPoolExecutor' at 0x7fe6a1e3fb80>, <_queue.SimpleQueue object at 0x7fe6a1e42e00>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
    │    └ <function _worker at 0x7fe6a1e55940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe6a1e55a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe6a1e96f40>, <grpc._server._RPCState object at 0x7fe6a1ea2190>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
             │    └ <function _unary_response_in_pool at 0x7fe6a1e93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe6a1e727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe6a1ea2190>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe6a1e96f40>
                        └ <function _call_behavior at 0x7fe6a1e92c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe6a1ea2100>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe6a1e727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 99, in CreateOrder
    id = local_order_dict[orderSn]["order"].id,
         │                └ '202208040337321236'
         └ {'202208040337151747': {'code': <StatusCode.NOT_FOUND: (5, 'not found')>, 'detail': '没有选择购物车商品'}, '202208040337321236': {'cod...

AttributeError: 'dict' object has no attribute 'id'
2022-08-04 03:37:33.002 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27727), thread 'ThreadPoolExecutor-0_0' (123145425432576):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe69fee7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe69fee79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
    │    │        │    └ (<weakref at 0x7fe6a1ea42c0; to 'ThreadPoolExecutor' at 0x7fe6a1e3fb80>, <_queue.SimpleQueue object at 0x7fe6a1e42e00>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
    │    └ <function _worker at 0x7fe6a1e55940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145425432576)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fe6a1e55a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fe6a1e96f40>, <grpc._server._RPCState object at 0x7fe6a1ea2190>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
             │    └ <function _unary_response_in_pool at 0x7fe6a1e93040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fe6a1ea2040>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe6a1e727c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fe6a1ea2190>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fe6a1e96f40>
                        └ <function _call_behavior at 0x7fe6a1e92c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fe6a1ea2100>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fe6a1e727c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 99, in CreateOrder
    id = local_order_dict[orderSn]["order"].id,
         │                └ '202208040337321236'
         └ {'202208040337151747': {'code': <StatusCode.NOT_FOUND: (5, 'not found')>, 'detail': '没有选择购物车商品'}, '202208040337321236': {'cod...

AttributeError: 'dict' object has no attribute 'id'
2022-08-04 03:37:51.546 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:37:51.546 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:37:51.546 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:37:53.379 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:37:53.379 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:37:53.379 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:38:04.736 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27779), thread 'ThreadPoolExecutor-0_0' (123145544474624):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdfdfeccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdfdfecc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
    │    │        │    └ (<weakref at 0x7fdfe2f7f220; to 'ThreadPoolExecutor' at 0x7fdfe2effb80>, <_queue.SimpleQueue object at 0x7fdfe2f12db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
    │    └ <function _worker at 0x7fdfe2f26940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fdfe2f26a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fdfe2f71e50>, <grpc._server._RPCState object at 0x7fdfe2f7d5e0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
             │    └ <function _unary_response_in_pool at 0x7fdfe2f6e040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fdfe2f437c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fdfe2f7d5e0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fdfe2f71e50>
                        └ <function _call_behavior at 0x7fdfe2f6cc10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fdfe2f7d1f0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fdfe2f437c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 101, in CreateOrder
    total = local_order_dict[orderSn]["order_id"].total,
            │                └ '202208040338041810'
            └ {'202208040338041810': {'code': <StatusCode.OK: (0, 'ok')>, 'detail': '订单创建成功', 'order': {'id': 46, 'order_sn': '202208040338...

KeyError: 'order_id'
2022-08-04 03:38:04.736 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27779), thread 'ThreadPoolExecutor-0_0' (123145544474624):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdfdfeccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdfdfecc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
    │    │        │    └ (<weakref at 0x7fdfe2f7f220; to 'ThreadPoolExecutor' at 0x7fdfe2effb80>, <_queue.SimpleQueue object at 0x7fdfe2f12db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
    │    └ <function _worker at 0x7fdfe2f26940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fdfe2f26a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fdfe2f71e50>, <grpc._server._RPCState object at 0x7fdfe2f7d5e0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
             │    └ <function _unary_response_in_pool at 0x7fdfe2f6e040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fdfe2f437c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fdfe2f7d5e0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fdfe2f71e50>
                        └ <function _call_behavior at 0x7fdfe2f6cc10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fdfe2f7d1f0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fdfe2f437c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 101, in CreateOrder
    total = local_order_dict[orderSn]["order_id"].total,
            │                └ '202208040338041810'
            └ {'202208040338041810': {'code': <StatusCode.OK: (0, 'ok')>, 'detail': '订单创建成功', 'order': {'id': 46, 'order_sn': '202208040338...

KeyError: 'order_id'
2022-08-04 03:38:04.736 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27779), thread 'ThreadPoolExecutor-0_0' (123145544474624):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdfdfeccca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fdfdfecc9d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
    │    │        │    └ (<weakref at 0x7fdfe2f7f220; to 'ThreadPoolExecutor' at 0x7fdfe2effb80>, <_queue.SimpleQueue object at 0x7fdfe2f12db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
    │    └ <function _worker at 0x7fdfe2f26940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145544474624)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fdfe2f26a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fdfe2f71e50>, <grpc._server._RPCState object at 0x7fdfe2f7d5e0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
             │    └ <function _unary_response_in_pool at 0x7fdfe2f6e040>
             └ <concurrent.futures.thread._WorkItem object at 0x7fdfe2f7d190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fdfe2f437c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7fdfe2f7d5e0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fdfe2f71e50>
                        └ <function _call_behavior at 0x7fdfe2f6cc10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fdfe2f7d1f0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fdfe2f437c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 101, in CreateOrder
    total = local_order_dict[orderSn]["order_id"].total,
            │                └ '202208040338041810'
            └ {'202208040338041810': {'code': <StatusCode.OK: (0, 'ok')>, 'detail': '订单创建成功', 'order': {'id': 46, 'order_sn': '202208040338...

KeyError: 'order_id'
2022-08-04 03:38:29.726 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:38:29.726 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:38:29.726 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:38:33.153 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:38:33.153 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:38:33.153 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:38:42.557 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27821), thread 'ThreadPoolExecutor-0_0' (123145601990656):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9f5b7e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9f5b7e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
    │    │        │    └ (<weakref at 0x7f9f5e686270; to 'ThreadPoolExecutor' at 0x7f9f5e610b80>, <_queue.SimpleQueue object at 0x7f9f5e623db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
    │    └ <function _worker at 0x7f9f5e637940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9f5e637a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9f5e678ea0>, <grpc._server._RPCState object at 0x7f9f5e6845e0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
             │    └ <function _unary_response_in_pool at 0x7f9f5e675040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9f5e6547c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9f5e6845e0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9f5e678ea0>
                        └ <function _call_behavior at 0x7f9f5e673c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9f5e6841f0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9f5e6547c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 98, in CreateOrder
    return order_pb2.OrderDetailResponse(
           │         └ <class 'order_pb2.OrderDetailResponse'>
           └ <module 'proto.order_pb2' from '/Users/www/learn-note/gpmall/daoServer/order/proto/order_pb2.py'>

ValueError: Protocol message OrderDetailResponse has no "total" field.
2022-08-04 03:38:42.557 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27821), thread 'ThreadPoolExecutor-0_0' (123145601990656):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9f5b7e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9f5b7e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
    │    │        │    └ (<weakref at 0x7f9f5e686270; to 'ThreadPoolExecutor' at 0x7f9f5e610b80>, <_queue.SimpleQueue object at 0x7f9f5e623db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
    │    └ <function _worker at 0x7f9f5e637940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9f5e637a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9f5e678ea0>, <grpc._server._RPCState object at 0x7f9f5e6845e0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
             │    └ <function _unary_response_in_pool at 0x7f9f5e675040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9f5e6547c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9f5e6845e0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9f5e678ea0>
                        └ <function _call_behavior at 0x7f9f5e673c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9f5e6841f0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9f5e6547c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 98, in CreateOrder
    return order_pb2.OrderDetailResponse(
           │         └ <class 'order_pb2.OrderDetailResponse'>
           └ <module 'proto.order_pb2' from '/Users/www/learn-note/gpmall/daoServer/order/proto/order_pb2.py'>

ValueError: Protocol message OrderDetailResponse has no "total" field.
2022-08-04 03:38:42.557 | ERROR    | grpc._server:_call_behavior:443 - An error has been caught in function '_call_behavior', process 'MainProcess' (27821), thread 'ThreadPoolExecutor-0_0' (123145601990656):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9f5b7e7ca0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9f5b7e79d0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
    │    │        │    └ (<weakref at 0x7f9f5e686270; to 'ThreadPoolExecutor' at 0x7f9f5e610b80>, <_queue.SimpleQueue object at 0x7f9f5e623db0>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
    │    └ <function _worker at 0x7f9f5e637940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145601990656)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7f9f5e637a60>
    └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7f9f5e678ea0>, <grpc._server._RPCState object at 0x7f9f5e6845e0>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
             │    └ <function _unary_response_in_pool at 0x7f9f5e675040>
             └ <concurrent.futures.thread._WorkItem object at 0x7f9f5e684190>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9f5e6547c0>>
                        │              │          └ <grpc._server._RPCState object at 0x7f9f5e6845e0>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7f9f5e678ea0>
                        └ <function _call_behavior at 0x7f9f5e673c10>
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7f9f5e6841f0>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7f9f5e6547c0>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 98, in CreateOrder
    return order_pb2.OrderDetailResponse(
           │         └ <class 'order_pb2.OrderDetailResponse'>
           └ <module 'proto.order_pb2' from '/Users/www/learn-note/gpmall/daoServer/order/proto/order_pb2.py'>

ValueError: Protocol message OrderDetailResponse has no "total" field.
2022-08-04 03:39:30.964 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:39:30.964 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:39:30.964 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:39:34.318 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:39:34.318 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:39:34.318 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:43:57.482 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:43:57.482 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:43:57.482 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:43:58.842 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:43:58.842 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:43:58.842 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 03:46:11.458 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:46:11.458 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 03:46:11.458 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 13:15:11.052 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 13:15:11.052 | INFO     | __main__:run:43 - service start...: 192.168.8.222:4347
2022-08-04 13:15:31.757 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-04 13:15:31.757 | INFO     | __main__:f:72 - 退出订单服务 service stop...:192.168.8.222:4347
