2022-08-06 18:36:55.160 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 18:36:55.160 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 18:36:55.160 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 19:09:51.227 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-2' (123145505325056):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131586816
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:09:51.227 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-2' (123145505325056):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131586816
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:09:51.227 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-2' (123145505325056):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131586816
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:10:01.310 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-3' (123145505861632):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131504384
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:10:01.310 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-3' (123145505861632):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131504384
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:10:01.310 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-3' (123145505861632):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131504384
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:10:31.325 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-4' (123145506398208):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131538944
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:10:31.325 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-4' (123145506398208):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131538944
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:10:31.325 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-4' (123145506398208):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131538944
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:11:31.334 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-5' (123145506934784):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131586560
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:11:31.334 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-5' (123145506934784):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131586560
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:11:31.334 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-5' (123145506934784):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131586560
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:13:31.371 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-6' (123145507471360):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131576576
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:13:31.371 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-6' (123145507471360):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131576576
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:13:31.371 | ERROR    | rocketmq.client:_on_message:396 - An error has been caught in function '_on_message', process 'MainProcess' (60061), thread 'Dummy-6' (123145507471360):
Traceback (most recent call last):

> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 396, in _on_message
    consume_result = callback(ReceivedMessage(msg))
                     │        │               └ 105553131576576
                     │        └ <class 'rocketmq.client.ReceivedMessage'>
                     └ <function timeout_order at 0x7fa15e61d430>

TypeError: timeout_order() missing 1 required positional argument: 'msg'
2022-08-06 19:15:22.312 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 19:15:22.312 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 19:15:22.312 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 19:15:24.685 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 19:15:24.685 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 19:15:24.685 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 19:16:54.605 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 19:16:54.605 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 19:16:54.605 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 19:59:12.358 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 19:59:12.358 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 19:59:12.358 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 19:59:22.061 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 19:59:22.061 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 19:59:22.061 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 20:00:12.572 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 20:00:12.572 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 20:00:12.572 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 21:29:10.107 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 21:29:10.107 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 21:29:10.107 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 22:39:40.648 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 22:39:40.648 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 22:39:40.648 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 22:41:05.196 | ERROR    | handler.order:local_execute:262 - An error has been caught in function 'local_execute', process 'MainProcess' (71441), thread 'ThreadPoolExecutor-0_0' (123145522003968):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa3de2cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa3de2cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
    │    │        │    └ (<weakref at 0x7fa3def71a40; to 'ThreadPoolExecutor' at 0x7fa3def13520>, <_queue.SimpleQueue object at 0x7fa3def11680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
    │    └ <function _worker at 0x7fa3def21af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fa3def21c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fa3def71950>, <grpc._server._RPCState object at 0x7fa3def64460>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
             │    └ <function _unary_response_in_pool at 0x7fa3def6d1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fa3def48160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fa3def64460>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fa3def71950>
                        └ <function _call_behavior at 0x7fa3def65dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fa3def7e070>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fa3def48160>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 114, in CreateOrder
    res = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fa3deee3310>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fa3def48160>
          │ │                           └ <rocketmq.client.Message object at 0x7fa3def7e310>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fa3de70ca60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fa3def7e0a0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553166440672
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7fa3def7e0a0>
    │   └ <_FuncPtr object at 0x7fa3de6fbe80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 2021a3ce0 at 0x7fa3de69a850>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='' body=b'{"order_sn": "202208062241041462", "user_id": 1, "signer_name": "\\u6bb5\\u8...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7fa3def48160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 262, in local_execute
    self.send_delay_order(orderSn)
    │    │                └ '202208062241041462'
    │    └ <function OrderServicer.send_delay_order at 0x7fa3deee39d0>
    └ <handler.order.OrderServicer object at 0x7fa3def48160>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 301, in send_delay_order
    if ret.status == grpc.SendStatus.OK:
       │   │         └ <module 'grpc' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/__init__.py'>
       │   └ _tuplegetter(0, 'Alias for field number 0')
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE17111771913E1E9DE8A60001', offset=83)

AttributeError: module 'grpc' has no attribute 'SendStatus'
2022-08-06 22:41:05.196 | ERROR    | handler.order:local_execute:262 - An error has been caught in function 'local_execute', process 'MainProcess' (71441), thread 'ThreadPoolExecutor-0_0' (123145522003968):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa3de2cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa3de2cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
    │    │        │    └ (<weakref at 0x7fa3def71a40; to 'ThreadPoolExecutor' at 0x7fa3def13520>, <_queue.SimpleQueue object at 0x7fa3def11680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
    │    └ <function _worker at 0x7fa3def21af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fa3def21c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fa3def71950>, <grpc._server._RPCState object at 0x7fa3def64460>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
             │    └ <function _unary_response_in_pool at 0x7fa3def6d1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fa3def48160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fa3def64460>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fa3def71950>
                        └ <function _call_behavior at 0x7fa3def65dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fa3def7e070>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fa3def48160>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 114, in CreateOrder
    res = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fa3deee3310>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fa3def48160>
          │ │                           └ <rocketmq.client.Message object at 0x7fa3def7e310>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fa3de70ca60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fa3def7e0a0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553166440672
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7fa3def7e0a0>
    │   └ <_FuncPtr object at 0x7fa3de6fbe80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 2021a3ce0 at 0x7fa3de69a850>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='' body=b'{"order_sn": "202208062241041462", "user_id": 1, "signer_name": "\\u6bb5\\u8...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7fa3def48160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 262, in local_execute
    self.send_delay_order(orderSn)
    │    │                └ '202208062241041462'
    │    └ <function OrderServicer.send_delay_order at 0x7fa3deee39d0>
    └ <handler.order.OrderServicer object at 0x7fa3def48160>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 301, in send_delay_order
    if ret.status == grpc.SendStatus.OK:
       │   │         └ <module 'grpc' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/__init__.py'>
       │   └ _tuplegetter(0, 'Alias for field number 0')
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE17111771913E1E9DE8A60001', offset=83)

AttributeError: module 'grpc' has no attribute 'SendStatus'
2022-08-06 22:41:05.196 | ERROR    | handler.order:local_execute:262 - An error has been caught in function 'local_execute', process 'MainProcess' (71441), thread 'ThreadPoolExecutor-0_0' (123145522003968):
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa3de2cbc10>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa3de2cb940>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
    │    │        │    └ (<weakref at 0x7fa3def71a40; to 'ThreadPoolExecutor' at 0x7fa3def13520>, <_queue.SimpleQueue object at 0x7fa3def11680>, None,...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
    │    └ <function _worker at 0x7fa3def21af0>
    └ <Thread(ThreadPoolExecutor-0_0, started daemon 123145522003968)>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x7fa3def21c10>
    └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
             │    │   │    └ (<grpc._cython.cygrpc.RequestCallEvent object at 0x7fa3def71950>, <grpc._server._RPCState object at 0x7fa3def64460>, <bound m...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
             │    └ <function _unary_response_in_pool at 0x7fa3def6d1f0>
             └ <concurrent.futures.thread._WorkItem object at 0x7fa3def7e130>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 560, in _unary_response_in_pool
    response, proceed = _call_behavior(rpc_event, state, behavior,
                        │              │          │      └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fa3def48160>>
                        │              │          └ <grpc._server._RPCState object at 0x7fa3def64460>
                        │              └ <grpc._cython.cygrpc.RequestCallEvent object at 0x7fa3def71950>
                        └ <function _call_behavior at 0x7fa3def65dc0>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           │        │         └ <grpc._server._Context object at 0x7fa3def7e070>
                           │        └ user_id: 1
                           │          name: "\346\256\265\350\266\205123"
                           │          mobile: "18612917508"
                           │          address: "\345\215\216\344\270\2551code"
                           │          
                           └ <bound method OrderServicer.CreateOrder of <handler.order.OrderServicer object at 0x7fa3def48160>>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 114, in CreateOrder
    res = p.send_message_in_transaction(msg, self.local_execute, user_args=None)
          │ │                           │    │    └ <function OrderServicer.local_execute at 0x7fa3deee3310>
          │ │                           │    └ <handler.order.OrderServicer object at 0x7fa3def48160>
          │ │                           └ <rocketmq.client.Message object at 0x7fa3def7e310>
          │ └ <function TransactionMQProducer.send_message_in_transaction at 0x7fa3de70ca60>
          └ <rocketmq.client.TransactionMQProducer object at 0x7fa3def7e0a0>

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 336, in send_message_in_transaction
    dll.SendMessageTransaction(self._handle,
    │   │                      │    └ 105553166440672
    │   │                      └ <rocketmq.client.TransactionMQProducer object at 0x7fa3def7e0a0>
    │   └ <_FuncPtr object at 0x7fa3de6fbe80>
    └ <CDLL '/usr/local/lib/librocketmq.dylib', handle 2021a3ce0 at 0x7fa3de69a850>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rocketmq/client.py", line 317, in _on_local_execute
    local_result = local_execute(py_message, usr_args)
                   │             │           └ None
                   │             └ <ReceivedMessage topic='transTopic' id='' body=b'{"order_sn": "202208062241041462", "user_id": 1, "signer_name": "\\u6bb5\\u8...
                   └ <bound method OrderServicer.local_execute of <handler.order.OrderServicer object at 0x7fa3def48160>>

> File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 262, in local_execute
    self.send_delay_order(orderSn)
    │    │                └ '202208062241041462'
    │    └ <function OrderServicer.send_delay_order at 0x7fa3deee39d0>
    └ <handler.order.OrderServicer object at 0x7fa3def48160>

  File "/Users/www/learn-note/gpmall/daoServer/order/handler/order.py", line 301, in send_delay_order
    if ret.status == grpc.SendStatus.OK:
       │   │         └ <module 'grpc' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/__init__.py'>
       │   └ _tuplegetter(0, 'Alias for field number 0')
       └ SendResult(status=<SendStatus.OK: 0>, msg_id='C0A808DE17111771913E1E9DE8A60001', offset=83)

AttributeError: module 'grpc' has no attribute 'SendStatus'
2022-08-06 22:53:44.582 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 22:53:44.582 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 22:53:44.582 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 22:53:55.434 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 22:53:55.434 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 22:53:55.434 | INFO     | __main__:run:44 - service start...: 192.168.8.222:4347
2022-08-06 23:02:01.260 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 23:02:01.260 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
2022-08-06 23:02:01.260 | INFO     | __main__:f:81 - 退出订单服务 service stop...:192.168.8.222:4347
